# Generated by Django 4.1.7 on 2023-02-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_products_codigo_products_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
