# Generated by Django 4.1.7 on 2023-02-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_products_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.AddField(
            model_name='department',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
