# Generated by Django 4.1.7 on 2023-02-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_department_description_department_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='descripcion',
            new_name='detalle',
        ),
    ]
