# Generated by Django 4.1.7 on 2023-03-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_rename_descripcion_department_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='imagen',
        ),
        migrations.AddField(
            model_name='products',
            name='product_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
