# Generated by Django 4.1.7 on 2023-03-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_remove_products_imagen_products_product_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_imagen',
            new_name='producto_imagen',
        ),
    ]
