# Generated by Django 4.1.7 on 2023-03-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_gallery_image_alter_products_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='producto_imagen',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
