# Generated by Django 4.1.7 on 2023-03-01 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_alter_products_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='producto_imagen',
        ),
    ]
