# Generated by Django 4.1.7 on 2023-03-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_rename_imagen_product_producto_imagen_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='producto_imagen',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
