# Generated by Django 4.1.7 on 2023-03-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_alter_product_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detalle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
