# Generated by Django 4.1.7 on 2023-03-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_product_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='precio',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
    ]
