# Generated by Django 4.1.7 on 2023-03-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_alter_product_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='producto_imagen',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
