# Generated by Django 4.1.7 on 2023-03-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_alter_product_producto_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
