# Generated by Django 4.1.7 on 2023-03-03 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_delete_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.tipomercancia'),
        ),
        migrations.AlterField(
            model_name='product',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.department'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producto_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
