# Generated by Django 4.1.7 on 2023-03-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_alter_product_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='producto_imagen',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
