# Generated by Django 4.1.7 on 2023-03-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0028_departamento_rename_created_tipomercancia_creado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
