# Generated by Django 4.1.7 on 2023-03-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_alter_departamento_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='activo',
            new_name='active',
        ),
    ]
